Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.network "public_network", ip: "192.168.0.226"
        ansible.vm.provision "shell",
            inline: "cp /vagrant/id_rsa_laguna_priv  /home/vagrant && \
                chmod 600 /home/vagrant/id_rsa_laguna_priv && \
                chown vagrant. id_rsa_laguna_priv"
        ansible.vm.provision "shell",
            inline: "apt-get update && \
                apt-get install -y software-properties-common && \
                apt-add-repository --yes --update ppa:ansible/ansible && \
                apt-get install -y ansible"
    end

    config.vm.define "wordpress" do |m|
        m.vm.network "private_network", ip: "172.17.177.40"
        m.vm.box = "ubuntu/trusty64"

        m.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end

        m.vm.provision "shell",
            inline: "cat /vagrant/id_rsa_laguna.pub >> .ssh/authorized_keys"
    end

    config.vm.define "mysql" do |m|
        m.vm.network "private_network", ip: "172.17.177.42"
        m.vm.box = "ubuntu/trusty64"

        m.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end

        m.vm.provision "shell",
            inline: "cat /vagrant/id_rsa_laguna.pub >> .ssh/authorized_keys"
    end

end